### ISSUE TITLE
Unable to install the version of Expo.

### ISSUE THREAD

**Issue by fungmo** [WrathChaos/react-native-dynamic-search-bar#40]
## No matter I use yarn or npm, I can't install it. 

![image](https://user-images.githubusercontent.com/16655229/104116879-6e234f00-5357-11eb-8c0c-b19fb7e2a36c.png)

## my version:
`"expo": "~40.0.0"`
`"react": "16.13.1"`
`"react-dom": "16.13.1"`
`"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz"`

**Comment by WrathChaos** [comment]
In your log, we can see that you have a network problem.

**Comment by mofengfs** [comment]
@WrathChaos 
I don't think it is a network problem, it may be that this library is not compatible with Expo40 and TypeScript.

![image](https://user-images.githubusercontent.com/16655229/104118078-328d8280-5361-11eb-8d6b-c950daa4e94f.png)

**Comment by WrathChaos** [comment]
Expo40 is just arrived never tried to work on it. I will try and fix it asap :) I will inform you today

**Comment by mofengfs** [comment]
> Expo40 is just arrived never tried to work on it. I will try and fix it asap :) I will inform you today

Many Thx

**Comment by andresribeiro** [comment]
I'm using Expo SDK 40 and it's working perfectly

**Comment by WrathChaos** [comment]
@mofengfs I've fixed the main path bug :) Can you please try it?

**Comment by mofengfs** [comment]
Sorry, still not possible

![image](https://user-images.githubusercontent.com/16655229/104310957-88079200-550f-11eb-859e-910ca10abf98.png)

**Comment by mofengfs** [comment]
> I'm using Expo SDK 40 and it's working perfectly

Can I take a look at your command line?

**Comment by andresribeiro** [comment]
> > I'm using Expo SDK 40 and it's working perfectly
> 
> Can I take a look at your command line?

![image](https://user-images.githubusercontent.com/63297375/104331411-cbd9a780-54cd-11eb-8b55-37f0e2770512.png)


I used Yarn, maybe it's a NPM error

**Comment by WrathChaos** [comment]
I can install it via NPM without a problem. @mofengfs Can you clean your npm cache? Because your local npm has a problem with it, also please upgrade the npm version.

**Comment by mofengfs** [comment]
@WrathChaos 
![image](https://user-images.githubusercontent.com/16655229/104457981-b0fa5680-55e5-11eb-8596-35a393d2adde.png)
I tried upgrading npm and clearing the cache, but it still doesn’t work
![image](https://user-images.githubusercontent.com/16655229/104458243-0d5d7600-55e6-11eb-86e6-bc747f602616.png)

**Comment by andresribeiro** [comment]
@mofengfs seems to be an NPM error. Try the same commands by opening the terminal as an administrator or re-install the NPM

**Comment by mofengfs** [comment]
@andresribeiro 
I tried to reinstall the new node and overwrite the old npm. It's still the same.

**Comment by andresribeiro** [comment]
> @andresribeiro 
> I tried to reinstall the new node and overwrite the old npm. It's still the same.

Can you install other packages with NPM?

**Comment by WrathChaos** [comment]
@mofengfs can you try another terminal? Like VSCode internal one?

**Comment by mofengfs** [comment]
@andresribeiro 
Yes, I can use npm to install other packages. But compared to yarn, it is still too slow.<br/>
![image](https://user-images.githubusercontent.com/16655229/104469502-8d3e0d00-55f3-11eb-9b57-7f4c93db172e.png)
<br/>
@WrathChaos 
Yes, I have tried to install with VScode terminal. <br/>
![image](https://user-images.githubusercontent.com/16655229/104469606-a9da4500-55f3-11eb-9043-3f4e6ae0644e.png)

**Comment by mofengfs** [comment]
@WrathChaos 
By the way, neither of my two computers can be installed.

**Comment by WrathChaos** [comment]
Finally fixed the problem. Can you please re-try to `npm i` if it's still not working please use this on your `package.json`: 

```
"react-native-dynamic-search-bar": "git+https://github.com/WrathChaos/react-native-dynamic-search-bar#expo",
```

**Comment by mofengfs** [comment]
> Finally fixed the problem. Can you please re-try to `npm i` if it's still not working please use this on your `package.json`:
> 
> ```
> "react-native-dynamic-search-bar": "git+https://github.com/WrathChaos/react-native-dynamic-search-bar#expo",
> ```
<br/>
I tried the npm installation first, without success. Then I added "react-native-dynamic-search-bar": "git+https://github.com/WrathChaos/react-native-dynamic-search-bar#expo "`to package.json.
But it stopped here. . .

<br/><br/>


![image](https://user-images.githubusercontent.com/16655229/104481750-1a3b9300-5601-11eb-8849-ff18a3ebf73d.png)

**Comment by mofengfs** [comment]
@WrathChaos 

It ended up reporting an error <br/>

![image](https://user-images.githubusercontent.com/16655229/104483710-638ce200-5603-11eb-843a-ae9216337129.png)

**Comment by WrathChaos** [comment]
@mofengfs I can literally be able to install the package into a fresh expo init project without a problem. Can you try to initialize a fresh project with:

```
expo init -t expo-template-blank-typescript test-exampl --npm
```

then

```
npm i WrathChaos/react-native-dynamic-search-bar#expo
```

**Comment by mofengfs** [comment]
@WrathChaos 
Sorry, this method is not suitable for me. It takes a long time to install dependent packages. There has been no response.

![image](https://user-images.githubusercontent.com/16655229/104602195-19186d80-56b6-11eb-8772-f2f6b568360a.png)
![image](https://user-images.githubusercontent.com/16655229/104606566-d9a05000-56ba-11eb-8e64-a1bc15cd1b7a.png)

**Comment by WrathChaos** [comment]
@mofengfs If you cannot even generate a fresh RN project, you definitely have some problems on the terminal side or your preferences or your network.

**Comment by mofengfs** [comment]
@WrathChaos 
I think It's NPM issues. the project can be generated. But if the dependencies are installed through NPM. Will fail.

**Comment by WrathChaos** [comment]
I think you need to uninstall whole node, npm and re-install again.

**Comment by mofengfs** [comment]
> I think you need to uninstall whole node, npm and re-install again.

I uninstalled Node.js and cleared the registry ->
Then install Node.js `current` version ->
Restart the computer ->
Recreate the project ->
`npm i WrathChaos/react-native-dynamic-search-bar#expo` ->
Failed

![image](https://user-images.githubusercontent.com/16655229/104805992-1b420f80-580f-11eb-83c0-cfa35aa328d3.png)

**Comment by WrathChaos** [comment]
@mofengfs Can you try my another expo supported library: 

```
npm i WrathChaos/react-native-dynamic-vector-icons#expo
```

Here is the library link: https://github.com/WrathChaos/react-native-dynamic-vector-icons

**Comment by mofengfs** [comment]
@WrathChaos 
I try it:

![image](https://user-images.githubusercontent.com/16655229/105579502-1dcdd780-5dc2-11eb-8504-5a21f3742208.png)

**Comment by WrathChaos** [comment]
I think you have a problem with installing sub-modules. Can you research about `git submodule`? What I do is just a sub-module on git that's it.

**Comment by fungmo** [comment]
Dear @WrathChaos ,

I am from China and I have a request.
Recently, a beacon-level figure was arrested by the Chinese government. He is an expert in cyber security, and he has evaded a decade of pursuit by the Chinese government. He is a teacher of enlightenment. He is also a thinker. No one knows his real name. He is like a lone ranger in the dark. He is like Zorro. His fraternity and spirit have influenced many people. His blog was nominated for the best Chinese blog in two monolingual awards (Public Award) in the 2013 Deutsche Welle International Blog Competition. He once said that if he hasn't been active on the entire platform for more than 14 days, either he will be caught by the Chinese government, or he will suffer serious personal injury. Since the last time he updated his blog on May 9th this year, he has no more activities. According to some sources, he was arrested by the Shanghai police.
I hope more people can support him and put pressure on the Chinese government (Communist Party). I don’t want heroes to be ignored. It’s really sad that our time still has Communist rule.

This is his blog: https://program-think.blogspot.com/
This is his github: https://github.com/programthink

Best Regards
